### ISSUE TITLE
test-sandbox-hunit-0.1.1 broken by HUnit update

### ISSUE THREAD

**Issue by peti** [gree/haskell-test-sandbox#20]
Please see http://hydra.cryp.to/build/1145197/log/raw for a complete build log.

**Comment by junjihashimoto** [comment]
Thank you for reporting the build-error.

By this pull requsest(https://github.com/gree/haskell-test-sandbox/pull/21), the error will be fixed.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by junjihashimoto** [comment]
Already done.

**Comment by peti** [comment]
Thanks!
